connect:
  handler: api/player/handler.connect
  events:
    - websocket:
        route: $connect

join:
  handler: api/player/handler.join
  events:
    - websocket:
        route: join

reconnect:
  handler: api/player/handler.reconnect
  events:
    - websocket:
        route: reconnect

disconnect:
  handler: api/player/handler.disconnect
  events:
    - websocket:
        route: $disconnect
default:
  handler: api/player/handler.defaults
  events:
    - websocket:
        route: $default

createGame:
  handler: api/game/handler.createGame
  events:
    - websocket:
        route: create

updateRound:
  handler: api/game/handler.updateRound
  events:
    - websocket:
        route: updateRound

updateCard:
  handler: api/playerDeck/handler.updateCard
  events:
    - websocket:
        route: updateCard

sendVote:
  handler: api/player/handler.sendVote
  events:
    - websocket:
        route: sendVote

endDiscuss:
  handler: api/player/handler.endDiscuss
  events:
    - websocket:
        route: endDiscuss
