## PLAYER

connect:
  handler: api/player/handler.connect
  events:
    - websocket:
        route: $connect

join:
  handler: api/player/handler.join
  events:
    - websocket:
        route: join

reconnect:
  handler: api/player/handler.reconnect
  events:
    - websocket:
        route: reconnect

disconnect:
  handler: api/player/handler.disconnect
  events:
    - websocket:
        route: $disconnect

default:
  handler: api/player/handler.defaults
  events:
    - websocket:
        route: $default

sendVote:
  handler: api/player/handler.sendVote
  events:
    - websocket:
        route: sendVote

endDiscuss:
  handler: api/player/handler.endDiscuss
  events:
    - websocket:
        route: endDiscuss

# CHAT

sendMessage:
  handler: api/chat/handler.sendMessage
  events:
    - websocket:
        route: sendMessage

# GAME

createGame:
  handler: api/game/handler.createGame
  events:
    - websocket:
        route: createGame

startGame:
  handler: api/game/handler.startGame
  events:
    - websocket:
        route: startGame

updateStatus:
  handler: api/game/handler.updateStatus
  events:
    - websocket:
        route: updateStatus

# PLAYER_DECK

updateCard:
  handler: api/playerDeck/handler.updateCard
  events:
    - websocket:
        route: updateCard
